# Generated by Django 5.2.4 on 2025-08-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='image/')),
                ('document', models.FileField(upload_to='file/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
