# Generated by Django 5.2.4 on 2025-09-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='itames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fess', models.IntegerField()),
            ],
        ),
    ]
